select CONCAT(d.tpodoccod, '-', d.doccor, '-', d.docanonum) TIPO_NUMERO_ANNO,
       d.docfchcre FEC_INGRESO, E.STSDSC ESTADO,
       D.DOCSOLNCMP SOLICITANTE , S.DNI DNI, S.RUC RUCM,
       D.DOCASU ASUNTO, D.DOCNUMFOL FOLIO,
       D.DOCUOACTCO, U.UNIORGNOM UO_ACTUAL,
       D.DOCCARACTC, C.CARDSC CARGO_ACTUAL,
       D.Docdirfisc DIRE_FISCAL, D.DOCDIRCORC DIR_CORRESPONDENCIA,D.DVIGUCDIR DIR_INMUEBLE,
       D.DOCOBS AS OBSERVACIONES, 
       D.DOCFLGHC AS HOJA_DE_CARGO, D.DOCFLGANX AS ANEXADO, D.DOCFLGARC AS ARCHIVADO,
       D.DOCUSRCRE, O.USRLOG AS USUARIO_CREACIO, D.DOCFCHCRE AS FEC_CREACION,
       D.DOCUSRMOD, m.usrlog as USUARIO_MODIFICA, D.DOCFCHMOD AS FEC_MOD
             
from tdddoc01 d, TDBEST01 E, IGRNTF03 S, RHDUOR01 U,rhbcar01 C, NSBUSR01 O, NSBUSR01 M
WHERE D.DOCSTSCOD = E.STSCOD AND D.DOCSOLCON = S.CON AND D.DOCUOACTCO= U.UNIORGCOD 
  AND D.DOCCARACTC= C.CARCOD AND D.DOCUSRCRE= O.USRCOD AND d.docusrmod = m.usrcod
  AND D.DOCANONUM = 2012
  AND D.DOCCOR >= 100
  and D.TPODOCCOD = 'EXPE'